language: cpp
os:
  - osx  
  - linux
env:
  - NODE_VERSION="0.10"
    JULIA_VERSION="juliareleases" 
  - NODE_VERSION="0.12"
    JULIA_VERSION="juliareleases" 
  - NODE_VERSION="0.12"
    JULIA_VERSION="julianightlies"
before_install:
  - if [ `uname` = "Linux" ]; then
      sudo add-apt-repository ppa:staticfloat/julia-deps -y;
      sudo add-apt-repository ppa:staticfloat/${JULIA_VERSION} -y;
      sudo apt-get update -qq -y;
      sudo apt-get install libpcre3-dev julia -y;
      nvm install $NODE_VERSION;
      npm install -g mocha chai sinon bindings node-gyp;
    elif [ `uname` = "Darwin" ]; then
      brew update;
      brew install nvm;
      source $(brew --prefix nvm)/nvm.sh;
      nvm install $NODE_VERSION;
      npm install -g mocha chai sinon bindings node-gyp;
      if [ "$JULIA_VERSION" = "julianightlies" ]; then
        wget -O julia.dmg "http://status.julialang.org/download/osx10.7+";
      else
        wget -O julia.dmg "http://status.julialang.org/stable/osx10.7+";
      fi;
      hdiutil mount julia.dmg;
      cp -Ra /Volumes/Julia/*.app/Contents/Resources/julia ~;
      export PATH=$PATH:~/julia/bin;
    fi
  - node --version
  - julia -e 'versioninfo()'
script:
  - npm install
  - npm test
